"""
Layer 2 Pydantic Schemas
Contracts for Query Understanding & Planning Layer.
Research basis:
- Q-DREAM (ACL 2025): Question Decomposition (QDM) & Dependency Optimizer (SDOM)
- Ammann et al. (ACL 2025): Drop-in multi-hop query decomposition
- DeCoR (CIKM 2025): Structured query expansion via reasoning steps
- AGR (ACL 2024): Analyze, Generate and Refine information need profiling
- MuGI (EMNLP 2024): Dual-channel sparse (BM25) and dense pseudo-reference expansion
- Knowledge-Aware QE (NAACL 2025): Relational triples & structural predicates
- Adaptive-RAG (NAACL 2024) & RealRoute (2026): Complexity-driven source routing (LOCAL_DOCS, LIVE_WEB, HYBRID)
- AtomRAG (2026): Atomic non-decomposable query criteria
- PROGRESS (2026): Coverage-based supervision
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from enum import Enum
from app.schemas.layer1 import StructuredUserInput, IntentCategory, QueryTypeCategory


class SourceTarget(str, Enum):
    LOCAL_DOCS = "LOCAL_DOCS"
    LIVE_WEB = "LIVE_WEB"
    HYBRID = "HYBRID"


class OutputExpectation(str, Enum):
    FACT = "FACT"
    SUMMARY = "SUMMARY"
    COMPARISON_ROW = "COMPARISON_ROW"
    CAUSAL_EXPLANATION = "CAUSAL_EXPLANATION"
    METRIC_DATA = "METRIC_DATA"


class InformationNeedProfile(BaseModel):
    """Sub-Module 2.1: Diagnoses what specific knowledge is missing (AGR ACL'24)."""
    known_anchors: List[str] = Field(default_factory=list, description="Entities, contexts or metrics already known from input")
    unknown_targets: List[str] = Field(default_factory=list, description="Target facts, figures or mechanisms required")
    evaluation_criteria: List[str] = Field(default_factory=list, description="Benchmarks, metrics, or comparison dimensions")
    target_domains: List[str] = Field(default_factory=list, description="Identified technical domains or subfields")
    complexity_level: str = Field("MODERATE", description="LOW, MODERATE, or HIGH complexity")


class SubQueryPlan(BaseModel):
    """
    Sub-query item generated by Decomposition (2.2),
    optimized by DAG (2.3), expanded by Multi-Representation (2.4),
    and routed by Source Router (2.5).
    """
    id: str = Field(..., description="Unique sub-query identifier, e.g. sq_1")
    description: str = Field(..., description="Semantic purpose of this sub-query")
    raw_sub_query: str = Field(..., description="Formulated sub-question")
    
    # DAG Scheduling (Q-DREAM SDOM ACL'25)
    depends_on: List[str] = Field(default_factory=list, description="IDs of sub-queries that must finish before this executes")
    stage_index: int = Field(0, description="Topological execution stage (0 = parallel first-wave)")
    
    # Dual-Channel Expansions (MuGI EMNLP'24, DeCoR CIKM'25, Knowledge-Aware NAACL'25)
    sparse_keywords: List[str] = Field(default_factory=list, description="Sparse keyword tokens for BM25 and exact indexing")
    dense_phrasings: List[str] = Field(default_factory=list, description="Alternative dense semantic sentences for vector similarity")
    relational_predicates: List[str] = Field(default_factory=list, description="Entity-relation triples, e.g., '(Entity, predicate, Object)'")
    
    # Dynamic Source Routing (Adaptive-RAG NAACL'24, RealRoute 2026)
    target_source: SourceTarget = Field(SourceTarget.LOCAL_DOCS, description="Routed source: LOCAL_DOCS, LIVE_WEB, or HYBRID")
    routing_reason: str = Field("", description="Justification for chosen source")
    
    expected_output_type: OutputExpectation = Field(OutputExpectation.FACT, description="Expected shape of retrieved answer")
    is_atomic: bool = Field(True, description="Conforms to AtomRAG atomic criteria")


class CoverageReport(BaseModel):
    """Sub-Module 2.2 PROGRESS (2026) coverage supervision verification."""
    is_fully_covered: bool = Field(True, description="Whether all key entities & constraints are represented")
    coverage_score: float = Field(1.0, ge=0.0, le=1.0, description="Fraction of covered key elements")
    covered_elements: List[str] = Field(default_factory=list)
    missing_elements: List[str] = Field(default_factory=list)


class KnowledgeRetrievalPlan(BaseModel):
    """
    Standardized typed contract outputted by Layer 2
    and consumed directly by Layer 3 (Knowledge Acquisition) & Layer 4 (Retrieval).
    """
    plan_id: str = Field(..., description="Unique plan UUID")
    session_id: str = Field(..., description="Session / conversation UUID")
    parent_query: str = Field(..., description="Resolved query from Layer 1")
    intent: IntentCategory = Field(..., description="Inherited intent from Layer 1")
    query_type: QueryTypeCategory = Field(..., description="Query typology")
    
    information_need: InformationNeedProfile
    coverage: CoverageReport
    sub_queries: List[SubQueryPlan] = Field(default_factory=list)
    
    # Topological Parallel Execution Schedule
    execution_stages: List[List[str]] = Field(
        default_factory=list,
        description="List of sub-query IDs grouped into concurrent waves: e.g. [['sq_1', 'sq_2'], ['sq_3']]"
    )
    is_parallel_executable: bool = Field(True, description="True if at least one stage contains multiple concurrent sub-queries")
    total_stages: int = Field(1, description="Number of sequential retrieval waves required")
    
    # Global Plan Metadata
    target_sources_summary: List[SourceTarget] = Field(default_factory=list, description="Unique sources needed across all sub-queries")
    global_constraints: List[str] = Field(default_factory=list, description="Temporal, format, or benchmark constraints")
    planning_time_ms: float = Field(..., description="Planning latency in milliseconds")


class Layer2DirectRequest(BaseModel):
    """For direct Layer 2 testing or when Layer 1 input contract is provided."""
    layer1_input: StructuredUserInput


class Layer2RawRequest(BaseModel):
    """For convenience when invoking Layer 2 directly with a raw query (runs Layer 1 internally)."""
    query: str = Field(..., min_length=1, max_length=5000)
    conversation_id: Optional[str] = None


class Layer2Response(BaseModel):
    status: str = "SUCCESS"
    plan: KnowledgeRetrievalPlan
