"""
Layer 2 FastAPI Router: Query Understanding & Planning
Endpoints for invoking Layer 2 planning and viewing execution plans.
"""

from fastapi import APIRouter, HTTPException, status
from app.schemas.layer1 import Layer1Request, Layer1Status
from app.schemas.layer2 import (
    Layer2DirectRequest,
    Layer2RawRequest,
    Layer2Response,
    KnowledgeRetrievalPlan
)
from app.core.layer1.pipeline import layer1_pipeline
from app.core.layer2.pipeline import layer2_pipeline

router = APIRouter(prefix="/layer2", tags=["Layer 2 - Query Understanding & Planning"])


@router.post("/plan", response_model=Layer2Response, summary="Generate retrieval plan from Layer 1 contract")
async def generate_plan_from_contract(request: Layer2DirectRequest):
    """
    Direct Layer 2 entrypoint.
    Accepts StructuredUserInput contract generated by Layer 1.
    """
    try:
        plan = layer2_pipeline.process(request.layer1_input)
        return Layer2Response(status="SUCCESS", plan=plan)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Layer 2 planning failed: {str(e)}"
        )


@router.post("/plan-raw", response_model=Layer2Response, summary="Execute Layer 1 + Layer 2 end-to-end")
async def generate_plan_from_raw_query(request: Layer2RawRequest):
    """
    Convenience end-to-end entrypoint:
    Runs Layer 1 (Interaction & Ambiguity Gating), verifies sufficiency,
    and if sufficient, pipes directly into Layer 2 (Query Planning).
    """
    l1_req = Layer1Request(query=request.query, conversation_id=request.conversation_id)
    l1_res = layer1_pipeline.process(l1_req)

    if l1_res.status == Layer1Status.CLARIFICATION_NEEDED:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail={
                "message": "Query requires clarification in Layer 1 before planning can proceed.",
                "clarification": l1_res.clarification.model_dump() if l1_res.clarification else None,
                "ambiguity": l1_res.ambiguity.model_dump()
            }
        )

    if l1_res.status == Layer1Status.REJECTED_INVALID:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Query rejected as invalid or malicious by Layer 1."
        )

    # Extract Layer 1 contract and execute Layer 2
    contract_dict = l1_res.contract_for_layer2
    if not contract_dict:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Layer 1 did not produce a valid contract for Layer 2."
        )

    from app.schemas.layer1 import StructuredUserInput
    structured_input = StructuredUserInput(**contract_dict)
    plan = layer2_pipeline.process(structured_input)
    return Layer2Response(status="SUCCESS", plan=plan)


@router.get("/health", summary="Layer 2 Health & Provider Status")
async def layer2_health():
    return {
        "layer": 2,
        "name": "Query Understanding & Planning Layer",
        "llm_provider": layer2_pipeline.llm_client.provider,
        "is_llm_configured": layer2_pipeline.llm_client._is_configured,
        "supported_sources": ["LOCAL_DOCS", "LIVE_WEB", "HYBRID"],
        "status": "HEALTHY"
    }
